### ISSUE TITLE
nosetest is failing

### ISSUE THREAD

**Issue by quantatanu** [brettviren/gegede#15]
Hi, 

I believe my [installation](https://github.com/brettviren/gegede/blob/master/doc/install.org) went fine. After step `python setup.py install` I skipped the "**Development**" section and went ahead to `nosetests` that failed, attaching the logs of `python3 setup.py develop` and `nosetests`

[nosetests.log](https://github.com/brettviren/gegede/files/7695441/nosetests.log)
[python3_setup.py_develop.log](https://github.com/brettviren/gegede/files/7695442/python3_setup.py_develop.log)

Can you please help me figure this out?

**Comment by brettviren** [comment]
Hi @quantatanu 

Your nosetests.log shows ROOT is segfaulting but I can't see any obvious telltale for why.

Has your ROOT been built with the same Python as being used to run GeGeDe?
 
In principle you may not need the ROOT / PyROOT binding to be working if your goal is to make GDML files.

**Comment by quantatanu** [comment]
Thanks for your prompt reply @brettviren should be the same python. But inside the venv, if I type `which python3` I get 
`my_ggd_path/GeGeDe_Python3_Dec_2021/ggdvenv/bin/python3`, to install ROOT I used `/usr/bin/python3` (version 3.8.10). I need ROOT to visualize my GDML file using `https://github.com/DUNE/dunendggd/blob/master/geoDisplay.C`

**Comment by brettviren** [comment]
If you do `ls -l $(which python3)` you'll see what python you really have.  Likely it points to your `/usr/bin/python3`.

If you run `root` from a shell environment that has not been set by your venv (eg, new terminal or run `deactivate`) are you able to load the GDML file okay?

**Comment by quantatanu** [comment]
`ls -l $(which python3)` returns `lrwxrwxrwx 1 root root 9 Nov 20 16:26 /usr/bin/python3 -> python3.8`

`root-config --has-python` returns `no` although I did pass the python argument while installing, attaching my ROOT install log: 
[cmake_log_root_build-v6-24-06_python3.log](https://github.com/brettviren/gegede/files/7695599/cmake_log_root_build-v6-24-06_python3.log)

Yes, from a root shell (outside the venv) GDML files load smoothly. It also loads while I am inside the venv and use the root shell.

**Comment by brettviren** [comment]
Okay.  Then, I think you can ignore this failing test.  

Or, if you wanted to use the PyROOT bindings with gegede we can continue to debug.  

In any case, next time I poke at gegede I'll exercise this test to see if I can reproduce the problem.

**Comment by quantatanu** [comment]
Great! Thank you so much for everything. I'll now go ahead and see if I can create a piece of geometry, I might face issues, in that case I will bother you again :(

**Comment by quantatanu** [comment]
By the way, I wrote to Guang Yang about an issue, but haven't got any replies yet so thought maybe it's something that you will solve just like that, so writing it down here, I am not sure if duneggd issue or GeGeDe though.


I was trying to run:

`gegede-cli duneggd/Config/PRIMggd_example.cfg duneggd/Config/DETENCLOSURE-prim-only.cfg duneggd/Config/WORLDggd.cfg -w World -o example.gdml`

but getting the following error message:

>Traceback (most recent call last):
  File "my_path/GeGeDe_Python3_Dec_2021/ggdvenv/lib/python3.8/site-packages/gegede-0.6.1-py3.8.egg/gegede/interp.py", line 28, in walk_builder_config_graph
    bdat = dat[bname]
KeyError: 'ND_Hall_Rock'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "my_path/GeGeDe_Python3_Dec_2021/ggdvenv/bin/gegede-cli", line 11, in <module>
    load_entry_point('gegede', 'console_scripts', 'gegede-cli')()
  File "my_path/GeGeDe_Python3_Dec_2021/ggdvenv/lib/python3.8/site-packages/gegede-0.6.1-py3.8.egg/gegede/main.py", line 95, in main
    wbuilder = make_builder(cfg, args.world)
  File "my_path/GeGeDe_Python3_Dec_2021/ggdvenv/lib/python3.8/site-packages/gegede-0.6.1-py3.8.egg/gegede/main.py", line 36, in make_builder
    return gegede.interp.make_builder(cfg, name)
  File "my_path/GeGeDe_Python3_Dec_2021/ggdvenv/lib/python3.8/site-packages/gegede-0.6.1-py3.8.egg/gegede/interp.py", line 17, in make_builder
    top = walk_builder_config_graph(dat, name, builder_objects)
  File "my_path/GeGeDe_Python3_Dec_2021/ggdvenv/lib/python3.8/site-packages/gegede-0.6.1-py3.8.egg/gegede/interp.py", line 38, in walk_builder_config_graph
    sb = walk_builder_config_graph(dat, sbname, builder_objects)
  File "my_path/GeGeDe_Python3_Dec_2021/ggdvenv/lib/python3.8/site-packages/gegede-0.6.1-py3.8.egg/gegede/interp.py", line 30, in walk_builder_config_graph
    print ('No such builder configuration section: "bname"' % bname)
TypeError: not all arguments converted during string formatting


By the way, this is my `python3 setup.py develop` output:


> running develop
running egg_info
writing dunendggd.egg-info/PKG-INFO
writing dependency_links to dunendggd.egg-info/dependency_links.txt
writing requirements to dunendggd.egg-info/requires.txt
writing top-level names to dunendggd.egg-info/top_level.txt
reading manifest file 'dunendggd.egg-info/SOURCES.txt'
writing manifest file 'dunendggd.egg-info/SOURCES.txt'
running build_ext
Creating /my_path/GeGeDe_Python3_Dec_2021/ggdvenv/lib/python3.8/site-packages/dunendggd.egg-link (link to .)
dunendggd 1.0.0 is already the active version in easy-install.pth

>Installed /my_path/ggd/GeGeDe_Python3_Dec_2021/dunendggd/DUNENDGGD
Processing dependencies for dunendggd==1.0.0
Searching for Pint==0.18
Best match: Pint 0.18
Processing Pint-0.18-py3.8.egg
Pint 0.18 is already the active version in easy-install.pth
Installing pint-convert script to /my_path/GeGeDe_Python3_Dec_2021/ggdvenv/bin

>Using /my_path/GeGeDe_Python3_Dec_2021/ggdvenv/lib/python3.8/site-packages/Pint-0.18-py3.8.egg
Searching for lxml==4.6.4
Best match: lxml 4.6.4
Processing lxml-4.6.4-py3.8-linux-x86_64.egg
lxml 4.6.4 is already the active version in easy-install.pth

>Using /my_path/GeGeDe_Python3_Dec_2021/ggdvenv/lib/python3.8/site-packages/lxml-4.6.4-py3.8-linux-x86_64.egg
Searching for gegede==0.6.1
Best match: gegede 0.6.1
Processing gegede-0.6.1-py3.8.egg
gegede 0.6.1 is already the active version in easy-install.pth
Installing gegede-cli script to /my_path/GeGeDe_Python3_Dec_2021/ggdvenv/bin

>Using /my_path/GeGeDe_Python3_Dec_2021/ggdvenv/lib/python3.8/site-packages/gegede-0.6.1-py3.8.egg
Searching for packaging==21.3
Best match: packaging 21.3
Processing packaging-21.3-py3.8.egg
packaging 21.3 is already the active version in easy-install.pth

>Using /my_path/GeGeDe_Python3_Dec_2021/ggdvenv/lib/python3.8/site-packages/packaging-21.3-py3.8.egg
Searching for nose==1.3.7
Best match: nose 1.3.7
Processing nose-1.3.7-py3.8.egg
nose 1.3.7 is already the active version in easy-install.pth
Installing nosetests script to /my_path/GeGeDe_Python3_Dec_2021/ggdvenv/bin
Installing nosetests-3.4 script to /my_path/GeGeDe_Python3_Dec_2021/ggdvenv/bin

>Using /my_path/GeGeDe_Python3_Dec_2021/ggdvenv/lib/python3.8/site-packages/nose-1.3.7-py3.8.egg
Searching for pyparsing==3.0.6
Best match: pyparsing 3.0.6
Processing pyparsing-3.0.6-py3.8.egg
pyparsing 3.0.6 is already the active version in easy-install.pth

>Using /my_path/GeGeDe_Python3_Dec_2021/ggdvenv/lib/python3.8/site-packages/pyparsing-3.0.6-py3.8.egg
Finished processing dependencies for dunendggd==1.0.0

**Comment by brettviren** [comment]
@quantatanu in your last comment, it looks like the configuration lacks a configuration for `ND_Hall_Rock`.  That's what initiates the error.  But, then it's clear that the `print()` is bad (should be a `,` instead `%`).  That definitely adds confusion to the error message.

On your end, you should see how to provide the complete config.
