### ISSUE TITLE
Python3 Functionality?

### ISSUE THREAD

**Issue by lopez86** [brettviren/gegede#2]
It looks like this is currently only compatible with Python 2 due to various minor issues with collections objects like OrderedDict plus changes to syntax for print and raising errors.

Should this package be made compatible with python 3? I'm working on getting a local version running since I have Root 6 with python 3 as my default environment on my laptop, but a python 3 version may not be backward compatible with python 2.

**Comment by brettviren** [comment]
Hi Jeremy.  I would very much like GeGeDe to be Python 3 compatible.  It's main "client" right now is DUNE and until FNAL moves to Python3 we have to keep Python2 compatibility.  If you are able to update GeGeDe to support both versions, I'd happily accept a PR!

**Comment by brettviren** [comment]
GeGeDe should be Python3.5 (and still Python2.7) compatible as of 4b36f998d959eefedb66b50502aaedfc01ffd740.

I don't have PyROOT for Python3 built so there may be some incompatibilities still lurking in code related to ROOT but as GDML is the main export I think things are good enough to call this issue closed.
