### ISSUE TITLE
Python version inconsistency

### ISSUE THREAD

**Issue by quantatanu** [brettviren/gegede#9]
Hi Brett,

this is not a GeGeDe issue though. I cloned this [duneggd](https://github.com/gyang9/dunendggd) (Guang & Jose), all their codes are written in python2.x, and they fail with ``gegede-cli``, once can translate all their code to ``python3`` of course and one had to if your GeGeDe weren't compatible with their codes, that would require translating a lot of codes. Fortunately, I could install GeGeDe on another venv named ggdvnv2 using python2.7, it went smooth and along with the nosetests. And I was able to use their duneggd to build DUNE ND detectors without any errors. In your install instructions, you have explicitly advised to use python3, but a few of us faced the same problems, I was wondering if you could add some optional instructions for python2.

Thanks

**Comment by brettviren** [comment]
In principle, GeGeDe itself should still work with Python 2.7 but the latest "pint" module has left Python2 behind.  So one would have to do some custom installation method to get an older version of "pint" that still supports Python 2.7.  

Gettng that kludge to work is probably more effort than upgrading `duneggd` to use Python 3.

FWIW, I translated all of GeGeDe to Python 3 while waiting for my car to get an oil change.  It was not much effort.

**Comment by quantatanu** [comment]
Thanks, as I have just begun to use python, it seemed tedious as duneggd had a lot of files, but maybe soon I will be able to translate them to python3.
